## override values.yaml with values to use for running on the NCEAS dev cluster
##
## example:
##
##  helm upgrade --install ${RELEASE_NAME} --debug -n %%APP_ABBREV_NAME%% \
##                          -f ./helm/examples/values-dev-cluster-example.yaml \
##                          oci://ghcr.io/dataoneorg/charts/%%APP_ABBREV_NAME%% --version [version]
##
## (or to install from local helm chart code, replace:
##  oci://ghcr.io/dataoneorg/charts/%%APP_ABBREV_NAME%% --version [version]
##  with: ./helm)
##
## see values.yaml for full documentation on the following parameters
##

global:
  ## Use your own release name instead of ${RELEASE_NAME}
  passwordsSecret: &passwordSecretName ${RELEASE_NAME}-%%APP_ABBREV_NAME%%-secrets

ns:
  logLevel: debug

postgresql:
  auth:
    existingSecret: *passwordSecretName
  primary:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 150m
        memory: 192Mi
    persistence:
      size: 10Gi

tomcat:
  jmxEnabled: false

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 300m
    memory: 128Mi

ingress:
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: &hostname %%APP_ABBREV_NAME%%.test.dataone.org
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - *hostname
      secretName: ingress-nginx-tls-cert
