Configuration:
  monitorInterval: 30  # seconds

  status: warn

  Appenders:
    Console:
      name: Console
      target: SYSTEM_OUT
      PatternLayout:
        pattern: "%%APP_FULL_NAME%% %d{yyyyMMdd-HH:mm:ss}: [%p]: %m [%C:%M:%L]%n"

  Loggers:
    Root:
      level: {{ .Values.%%APP_ABBREV_NAME%%.logLevel | default "warn" }}
      AppenderRef:
        ref: Console
    Logger:
      - name: org.jboss
        level: warn
        additivity: false
        AppenderRef:
          ref: Console
      - name: com.zaxxer.hikari.pool
        level: warn
        additivity: false
        AppenderRef:
          ref: Console
